language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn lint
  - yarn test:coverage
  - codecov
on:
  branch: master
